module.exports = {
    Default: {
        "Kick" : "./audio/drum/kick.mp3",
        "Snare" : "./audio/drum/snare.mp3",
        "Hi-hat" : "./audio/drum/hihat.mp3",
        "Tom" : "./audio/drum/tom.mp3",
    	"A" : "./audio/casio/A1.mp3",
    	"C#" : "./audio/casio/Cs2.mp3",
    	"E" : "./audio/casio/E2.mp3",
    	"F#" : "./audio/casio/Fs2.mp3",
    },
    Casio: {
    	"C" : "./audio/casio/C2.mp3",
    	"D" : "./audio/casio/D2.mp3",
    	"E" : "./audio/casio/E2.mp3",
    	"F" : "./audio/casio/F2.mp3",
    	"G" : "./audio/casio/G2.mp3",
    	"A" : "./audio/casio/A2.mp3",
    	"B" : "./audio/casio/B1.mp3",
    	"F#" : "./audio/casio/Fs2.mp3",
    },
    French_Toast: {
    	"Kick" : "./audio/french-toast/french-toast-kick.mp3",
    	"Snare" : "./audio/french-toast/french-toast-snare.mp3",
    	"Hi-Hat" : "./audio/french-toast/french-toast-hihat.mp3",
    	"Punch" : "./audio/french-toast/french-toast-punch.mp3",
    	"C" : "./audio/juno-106/juno-106-c.mp3",
    	"E" : "./audio/juno-106/juno-106-e.mp3",
    	"G" : "./audio/juno-106/juno-106-g.mp3",
    	"A" : "./audio/juno-106/juno-106-a.mp3",
    },
    Bulldog: {
    	"Kick" : "./audio/bulldog/bulldog-kick.mp3",
    	"Snare" : "./audio/bulldog/bulldog-snare.mp3",
    	"Hi-Hat 1" : "./audio/bulldog/bulldog-hihat-1.mp3",
    	"Hi-Hat 2" : "./audio/bulldog/bulldog-hihat-2.mp3",
    	"Synth-1" : "./audio/bulldog/bulldog-synth-1.mp3",
    	"Synth-2" : "./audio/bulldog/bulldog-synth-2.mp3",
    	"Synth-3" : "./audio/bulldog/bulldog-synth-3.mp3",
    	"Tom" :  "./audio/bulldog/bulldog-tom.mp3",
    },
    Juno_106: {
    	"C" : "./audio/juno-106/juno-106-c.mp3",
    	"D" : "./audio/juno-106/juno-106-d.mp3",
    	"E" : "./audio/juno-106/juno-106-e.mp3",
    	"F" : "./audio/juno-106/juno-106-f.mp3",
    	"G" : "./audio/juno-106/juno-106-g.mp3",
    	"A" : "./audio/juno-106/juno-106-a.mp3",
    	"B" : "./audio/juno-106/juno-106-b.mp3",
    	"C2"  : "./audio/juno-106/juno-106-c2.mp3",
    },
    Rhodes_Minor: {
    	"A" : "./audio/rhodes-minor/rhodes-m-a.mp3",
    	"B" : "./audio/rhodes-minor/rhodes-m-b.mp3",
    	"C" : "./audio/rhodes-minor/rhodes-m-c.mp3",
    	"D" : "./audio/rhodes-minor/rhodes-m-d.mp3",
    	"E" : "./audio/rhodes-minor/rhodes-m-e.mp3",
    	"F" : "./audio/rhodes-minor/rhodes-m-f.mp3",
    	"G" : "./audio/rhodes-minor/rhodes-m-g.mp3",
    	"A2" : "./audio/rhodes-minor/rhodes-m-a2.mp3",
    },
    Rhodes_Major: {
    	"C" : "./audio/rhodes-major/rhodes-c.mp3",
    	"D" : "./audio/rhodes-major/rhodes-d.mp3",
    	"E" : "./audio/rhodes-major/rhodes-e.mp3",
    	"F" : "./audio/rhodes-major/rhodes-f.mp3",
    	"G" : "./audio/rhodes-major/rhodes-g.mp3",
    	"A" : "./audio/rhodes-major/rhodes-a.mp3",
    	"B" : "./audio/rhodes-major/rhodes-b.mp3",
    	"C2": "./audio/rhodes-major/rhodes-c2.mp3",
    },
    Sine_Bass: {
    	"C" : "./audio/sine-bass/sine-bass-c.mp3",
    	"D" : "./audio/sine-bass/sine-bass-d.mp3",
    	"E" : "./audio/sine-bass/sine-bass-e.mp3",
    	"F" : "./audio/sine-bass/sine-bass-f.mp3",
    	"G" : "./audio/sine-bass/sine-bass-g.mp3",
    	"A" : "./audio/sine-bass/sine-bass-a.mp3",
    	"B" : "./audio/sine-bass/sine-bass-b.mp3",
    	"C2": "./audio/sine-bass/sine-bass-c2.mp3",
    },
    
    
    
};
